### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by sunny81599** [payatu/iBugBazaar#9]
I install this IPA in iPhone but show error. my Device iOS Version:-(16.6) & Device Model iPhone 8 Plus.

![2023-12-18_10h43_02](https://github.com/payatu/iBugBazaar/assets/88844693/a92f3cf7-c957-4694-a277-336861e0b589)
![IMG_20231218_104242](https://github.com/payatu/iBugBazaar/assets/88844693/68ebe953-7742-4c0c-b4d9-6a4397a577c0)

**Comment by banditkapil** [comment]
Redownload the application and check again

**Comment by sunny81599** [comment]
Ok Thank you so much sir.

**Comment by banditkapil** [comment]
Its resolved @banditAmit

**Comment by sunny81599** [comment]
Yes, it worked.
